steps:
# 步驟 1: 使用 Dockerfile 建置 Docker 映像檔
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/order-app:$COMMIT_SHA', '.']

# 步驟 2: 將建置好的 Docker 映像檔推送到 Google Container Registry (gcr.io)
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/order-app:$COMMIT_SHA']

# 步驟 3: 將映像檔部署到 Google Cloud Run
# cloud-sdk 工具包含 gcloud 指令
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'order-app' # 部署的服務名稱
  - '--image=gcr.io/$PROJECT_ID/order-app:$COMMIT_SHA'
  - '--region=us-central1' # 選擇您想部署的區域
  - '--platform=managed'
  - '--allow-unauthenticated' # 允許未經驗證的存取，若需要登入才能使用，請移除此行